spring:
    data:
        mongodb:
            uri: mongodb://localhost/funmarket
    thymeleaf:
        cache: false

server:
    port: 8080

---

spring:
    profiles: heroku
    data:
        mongodb:
            uri: ${MONGOLAB_URI}/funmarket
    thymeleaf:
        cache: true

server:
    port: ${PORT}